name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get release version
        id: vars
        run: |
          VERSION="${GITHUB_REF_NAME}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/keycloak-playground:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/keycloak-playground:${{ steps.vars.outputs.version }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/keycloak-playground-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/keycloak-playground-backend:${{ steps.vars.outputs.version }}

      - name: Done
        run: |
          echo "Images pushed successfully!"
          echo "Frontend: ${{ secrets.DOCKERHUB_USERNAME }}/keycloak-playground:${{ steps.vars.outputs.version }}"
          echo "Backend:  ${{ secrets.DOCKERHUB_USERNAME }}/keycloak-playground-backend:${{ steps.vars.outputs.version }}"
